### ISSUE TITLE
Should the root scripts be more complete?

### ISSUE THREAD

**Issue by MichalBryxi** [NullVoxPopuli/ember-addon-migrator#11]
What I got after the run of `ember-addon-migrator` is:

```json
  "scripts": {
    "build": "yarn workspace ember-intl-changeset-validations build",
    "prepare": "yarn build"
  },
```

Should it contain [(some) parts of](https://github.com/NullVoxPopuli/ember-popperjs/pull/142/files):

```json
  "scripts": {
    "start": "concurrently 'npm:watch:*'",
    "build": "concurrently 'npm:build:*'",
    "build:js": "rollup -c ./rollup.config.js",
    "build:docs": "cp ../README.md ./README.md",
    "watch:js": "rollup -c --watch --no-watch.clearScreen",
    "lint": "concurrently 'npm:lint:js'",
    "lint:fix": "concurrently 'npm:lint:js:fix'",
    "lint:js": "eslint . --cache",
    "lint:js:fix": "eslint . --fix",
    "test": "echo 'Addon does not have tests, run tests in test-app'",
    "prepare": "yarn run build",
    "prepublishOnly": "yarn run build"
  },
```

I _think_:
 - `test` is universally applicable?
 - `lint*` should also work in most of addons?
 - making `start` work would be quite beneficial?

**Comment by NullVoxPopuli** [comment]
I suppose 🤷 
PRs welcome. 
Would need to add concurrently to the root package.json, i think, becouse i'd expect start to do watch mode everywhere

**Comment by NullVoxPopuli** [comment]
For _full migration_ (default command), this happens automatically due to these scripts being defined in the v2 addon blueprint's root package.json.

Lemme know if anything is missing!
