### ISSUE TITLE
Way to preserve/update original eslint config

### ISSUE THREAD

**Issue by lifeart** [NullVoxPopuli/ember-addon-migrator#17]
Right now we found that 

```js
const { configs } = require('@nullvoxpopuli/eslint-configs');
```

this line is added to 

https://github.com/NullVoxPopuli/ember-addon-migrator/blob/main/src/js/files/.eslintrc.cjs#L3

Wondering, how I can help here to support original eslint config (with some mutation)

**Comment by NullVoxPopuli** [comment]
I think it could be possible to retain original config via codemod (jscodeshift): https://ember-apply.pages.dev/modules/js#transform
```js
await fse.move('.eslintrc.js', '<addon-path>/.eslintrc.js');
await js.transform('<addon-path>/.eslintrc.js', ({ root, j }) => {
  // remove all references to app
  // rename all "addon" to "src"
  // remove entries to ember-specific files
  // ensure CJS/ESM/MJS extensions are setup for the `.*` (root addon directory) files
});

```

**Comment by lifeart** [comment]
@NullVoxPopuli I'm thinking about file structure, we could have 

`src/transforms/{originalFilePath__originalFileName}` with 2 exports: 

```ts
{ 
  filePath: string;
  async transform(content, meta = {}): string;
}
```

**Comment by nicolechung** [comment]
I think this is fixed now with this? https://github.com/NullVoxPopuli/ember-addon-migrator/pull/79/files
