### ISSUE TITLE
Should /config/* files be preserved?

### ISSUE THREAD

**Issue by MichalBryxi** [NullVoxPopuli/ember-addon-migrator#35]
I [tried to use this on one of my addons](https://gitlab.com/michal-bryxi/open-source/ember-safe-button/-/merge_requests/195/diffs?commit_id=be19214fa1adfa6485059f65b38c5de7aba97856#43e37531dfab7a45391dd6a05e4ba311caf78b53) and it seems to me like it did not copy all files in `/config/` directory?

Before I had there `config/tailwindcss-config.js`. I'm not 100% how legit this request is as I was intentionally installing tailwind for the documentation site that was using [ember-cli-addon-docs](https://github.com/ember-learn/ember-cli-addon-docs). Going to refactor this anyway so maybe this is an extra odd thing to do anyway? Not sure.

**Comment by NullVoxPopuli** [comment]
the top level config usually isn't used for the dummy app -- it's a confusing directory anyway, and I don't know what to do with it -- I think it's scoped _to the addon_, rather than the dummy app.

the config that I would expect to be copied over is `tests/dummy/config/*`

:shrug:

**Comment by MichalBryxi** [comment]
Fair. My setup might have been just odd. Maybe this bug report will help someone.
