### ISSUE TITLE
extract-tests, tsconfig.compiler-options, extends

### ISSUE THREAD

**Issue by nicolechung** [NullVoxPopuli/ember-addon-migrator#65]
Because the migrator moves the source code from `/addon` to `/package/addon`, a change to `extends` in the `package/tsconfig.compiler-options.json` is needed:

```diff
{
+  extends: "tsconfig.compiler-options.my-custom-options.json"
-  extends: "../tsconfig.compiler-options.my-custom-options.json"
}
```

Not sure if this is something that can be automated, or should just be documented?

**Comment by NullVoxPopuli** [comment]
I think it can be automated, and would be worth doing!
