### ISSUE TITLE
extract-tests, references need updating in tsconfigs

### ISSUE THREAD

**Issue by nicolechung** [NullVoxPopuli/ember-addon-migrator#66]
Because the source code moves from `addon` to `package/addon` a change in the paths in references in the `tsconfig` is needed:

```diff
"references": [
    {
-      "path": "my-package"
+      "path": "../my-package"
    }
]
```

Similar to https://github.com/NullVoxPopuli/ember-addon-migrator/issues/65, not sure if this is something that can be automated or something that should be documented?

**Comment by NullVoxPopuli** [comment]
I think it can be automated and is worth doing!

**Comment by simonihmig** [comment]
Closed by https://github.com/NullVoxPopuli/ember-addon-migrator/pull/74
